--EL İLE YAZILDI 
CREATE TABLE public.users(
	id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 214748647 CACHE 1),
	email CHARACTER VARYING(320) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY(id),
	CONSTRAINT uc_users_email UNIQUE(email)

);

CREATE TABLE public.system_users(
	id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	CONSTRAINT pk_system_user PRIMARY KEY(id),
	CONSTRAINT fk_system_users_users FOREIGN KEY(id) REFERENCES public.users(id)
);

CREATE TABLE public.candidates(
	id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	identity_number INT NOT NULL,
	birth_year INT NOT NULL,
	CONSTRAINT pk_candidates PRIMARY KEY(id),
	CONSTRAINT fk_candidates_users FOREIGN KEY(id) REFERENCES public.users(id),
	CONSTRAINT uc_candidates_identity_numver UNIQUE(identity_number)
);

CREATE TABLE public.employers(
	id INT NOT NULL,
	company_name CHARACTER VARYING(40) NOT NULL,
	web_adress CHARACTER VARYING(100) NOT NULL,
	phone_number CHARACTER VARYING(12) NOT NULL,
	CONSTRAINT pk_employers_id PRIMARY KEY(id),
 	CONSTRAINT fk_employers_id FOREIGN KEY(id) REFERENCES public.users(id)	
);

CREATE TABLE public.verification_codes(
	id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 214748647 CACHE 1),
	code CHARACTER VARYING(38) NOT NULL,
	is_verified  BOOLEAN NOT NULL,
	verified_date DATE,
	CONSTRAINT pk_verification_codes PRIMARY KEY(id),
	CONSTRAINT uc_verification_codes_code UNIQUE(code)
); 

CREATE TABLE public.verification_code_candidates(
	id INT NOT NULL,
	candidate_id INT NOT NULL,
	CONSTRAINT pk_verification_code_candidates PRIMARY KEY(id),
	CONSTRAINT fk_verification_code_candidates_verification_codes FOREIGN KEY(id) REFERENCES public.verification_codes(id),
    CONSTRAINT fk_verification_code_candidates_candidates FOREIGN KEY(candidate_id) REFERENCES public.candidates(id)
);

CREATE table public.verification_code_employers(
	id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_verification_code_employers PRIMARY KEY(id),
	CONSTRAINT fk_verification_code_employers_verification_codes FOREIGN KEY(id) REFERENCES public.verification_codes(id),
    CONSTRAINT fk_verification_code_candidates_candidates FOREIGN KEY(employer_id) REFERENCES public.employers(id)
);

CREATE TABLE system_user_confirms(
	id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 214748647 CACHE 1),
	system_user_id INT NOT NULL,
	is_confirmed BOOLEAN NOT NULL,
	confirm_date DATE,
	CONSTRAINT pk_system_user_confirms PRIMARY KEY(id),
	CONSTRAINT fk_system_user_confirms_system_users FOREIGN KEY(system_user_id) REFERENCES public.system_users(id)

);

CREATE TABLE system_user_confirm_employers(
	id INT NOT NULL,
	employer_id INT,
	CONSTRAINT pk_system_user_confirm_employers PRIMARY KEY(id),
	CONSTRAINT fk_system_user_confirm_employers_system_user_confirms FOREIGN KEY(id) REFERENCES public.system_user_confirms(id),
	CONSTRAINT fk_system_user_confirm_employers_employers FOREIGN KEY(employer_id) REFERENCES public.employers(id)
);

CREATE TABLE job_titles(
	id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 214748647 CACHE 1),
	title CHARACTER VARYING(255),
	CONSTRAINT pk_job_titles PRIMARY KEY(id),
	CONSTRAINT uc_job_titles_title UNIQUE(title)
);